version: "3.9"
services:
  ### Postgres Database ###
  postgres:
    image: postgres
    ports:
      - "35001:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: storagedb
  ### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5051:80"
  ### API Spring Boot ###
  storage_api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:5432/storagedb
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    ports:
      - "8084:3031"